name: Upload AtCoder Submissions

on:
  schedule:
    # Every Monday at 00:00 JST
    - cron: "0 15 * * MON"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install get-chrome-driver --upgrade
          pip install -r scripts/requirements.txt

      - name: Fetch AtCoder submissions
        run: python scripts/fetch_atcoder_submissions.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --locla user.email "github-actions[bot]@users.noreply.github.com"
          git config --locla user.name "github-actions[bot]"
          git add submissions/
          git commit -m "Update AtCoder submissions"
          git push
